config/routes.rb
Promo::Application.routes.draw do

  resources :traffic_sources

  resources :affiliate_networks

end

app/models/affiliate_network.rb
class AffiliateNetwork < ActiveRecord::Base
end

app/models/traffic_source.rb
class TrafficSource < ActiveRecord::Base
end

app/controllers/affiliate_networks_controller.rb
class AffiliateNetworksController < ApplicationController
  # GET /affiliate_networks
  # GET /affiliate_networks.xml
  def index
    @affiliate_networks = AffiliateNetwork.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @affiliate_networks }
    end
  end

  # GET /affiliate_networks/1
  # GET /affiliate_networks/1.xml
  def show
    @affiliate_network = AffiliateNetwork.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @affiliate_network }
    end
  end

  # GET /affiliate_networks/new
  # GET /affiliate_networks/new.xml
  def new
    @affiliate_network = AffiliateNetwork.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @affiliate_network }
    end
  end

  # GET /affiliate_networks/1/edit
  def edit
    @affiliate_network = AffiliateNetwork.find(params[:id])
  end

  # POST /affiliate_networks
  # POST /affiliate_networks.xml
  def create
    @affiliate_network = AffiliateNetwork.new(params[:affiliate_network])

    respond_to do |format|
      if @affiliate_network.save
        format.html { redirect_to(@affiliate_network, :notice => 'Affiliate network was successfully created.') }
        format.xml  { render :xml => @affiliate_network, :status => :created, :location => @affiliate_network }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @affiliate_network.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /affiliate_networks/1
  # PUT /affiliate_networks/1.xml
  def update
    @affiliate_network = AffiliateNetwork.find(params[:id])

    respond_to do |format|
      if @affiliate_network.update_attributes(params[:affiliate_network])
        format.html { redirect_to(@affiliate_network, :notice => 'Affiliate network was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @affiliate_network.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /affiliate_networks/1
  # DELETE /affiliate_networks/1.xml
  def destroy
    @affiliate_network = AffiliateNetwork.find(params[:id])
    @affiliate_network.destroy

    respond_to do |format|
      format.html { redirect_to(affiliate_networks_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/traffic_sources_controller.rb
class TrafficSourcesController < ApplicationController
  # GET /traffic_sources
  # GET /traffic_sources.xml
  def index
    @traffic_sources = TrafficSource.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @traffic_sources }
    end
  end

  # GET /traffic_sources/1
  # GET /traffic_sources/1.xml
  def show
    @traffic_source = TrafficSource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @traffic_source }
    end
  end

  # GET /traffic_sources/new
  # GET /traffic_sources/new.xml
  def new
    @traffic_source = TrafficSource.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @traffic_source }
    end
  end

  # GET /traffic_sources/1/edit
  def edit
    @traffic_source = TrafficSource.find(params[:id])
  end

  # POST /traffic_sources
  # POST /traffic_sources.xml
  def create
    @traffic_source = TrafficSource.new(params[:traffic_source])

    respond_to do |format|
      if @traffic_source.save
        format.html { redirect_to(@traffic_source, :notice => 'Traffic source was successfully created.') }
        format.xml  { render :xml => @traffic_source, :status => :created, :location => @traffic_source }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @traffic_source.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /traffic_sources/1
  # PUT /traffic_sources/1.xml
  def update
    @traffic_source = TrafficSource.find(params[:id])

    respond_to do |format|
      if @traffic_source.update_attributes(params[:traffic_source])
        format.html { redirect_to(@traffic_source, :notice => 'Traffic source was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @traffic_source.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /traffic_sources/1
  # DELETE /traffic_sources/1.xml
  def destroy
    @traffic_source = TrafficSource.find(params[:id])
    @traffic_source.destroy

    respond_to do |format|
      format.html { redirect_to(traffic_sources_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/affiliate_networks_helper.rb
module AffiliateNetworksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/traffic_sources_helper.rb
module TrafficSourcesHelper
end

app/views/affiliate_networks/_form.html.erb
<%= form_for(@affiliate_network) do |f| %>
  <% if @affiliate_network.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@affiliate_network.errors.count, "error") %> prohibited this affiliate_network from being saved:</h2>

      <ul>
      <% @affiliate_network.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/affiliate_networks/edit.html.erb
<h1>Editing affiliate_network</h1>

<%= render 'form' %>

<%= link_to 'Show', @affiliate_network %> |
<%= link_to 'Back', affiliate_networks_path %>

app/views/affiliate_networks/index.html.erb
<h1>Listing affiliate_networks</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @affiliate_networks.each do |affiliate_network| %>
  <tr>
    <td><%= affiliate_network.name %></td>
    <td><%= link_to 'Show', affiliate_network %></td>
    <td><%= link_to 'Edit', edit_affiliate_network_path(affiliate_network) %></td>
    <td><%= link_to 'Destroy', affiliate_network, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Affiliate network', new_affiliate_network_path %>

app/views/affiliate_networks/new.html.erb
<h1>New affiliate_network</h1>

<%= render 'form' %>

<%= link_to 'Back', affiliate_networks_path %>

app/views/affiliate_networks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @affiliate_network.name %>
</p>


<%= link_to 'Edit', edit_affiliate_network_path(@affiliate_network) %> |
<%= link_to 'Back', affiliate_networks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Promo</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/traffic_sources/_form.html.erb
<%= form_for(@traffic_source) do |f| %>
  <% if @traffic_source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@traffic_source.errors.count, "error") %> prohibited this traffic_source from being saved:</h2>

      <ul>
      <% @traffic_source.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :user_account %><br />
    <%= f.text_field :user_account %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/traffic_sources/edit.html.erb
<h1>Editing traffic_source</h1>

<%= render 'form' %>

<%= link_to 'Show', @traffic_source %> |
<%= link_to 'Back', traffic_sources_path %>

app/views/traffic_sources/index.html.erb
<h1>Listing traffic_sources</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>User account</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @traffic_sources.each do |traffic_source| %>
  <tr>
    <td><%= traffic_source.name %></td>
    <td><%= traffic_source.type %></td>
    <td><%= traffic_source.user_account %></td>
    <td><%= link_to 'Show', traffic_source %></td>
    <td><%= link_to 'Edit', edit_traffic_source_path(traffic_source) %></td>
    <td><%= link_to 'Destroy', traffic_source, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Traffic source', new_traffic_source_path %>

app/views/traffic_sources/new.html.erb
<h1>New traffic_source</h1>

<%= render 'form' %>

<%= link_to 'Back', traffic_sources_path %>

app/views/traffic_sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @traffic_source.name %>
</p>

<p>
  <b>Type:</b>
  <%= @traffic_source.type %>
</p>

<p>
  <b>User account:</b>
  <%= @traffic_source.user_account %>
</p>


<%= link_to 'Edit', edit_traffic_source_path(@traffic_source) %> |
<%= link_to 'Back', traffic_sources_path %>